# Generated by Django 5.2.1 on 2025-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_donation',
            name='Donation_date',
            field=models.DateTimeField(),
        ),
    ]
