# Generated by Django 5.2.1 on 2025-06-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
