# Generated by Django 5.2.1 on 2025-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cct', '0002_alter_add_donation_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_donation',
            name='Quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=255, max_digits=50),
        ),
    ]
