# Generated by Django 5.2.1 on 2025-06-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cct', '0002_remove_donation_recipient_remove_donation_user_and_more'),
    ]

    operations = [
         migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
